### ISSUE TITLE
Error in downloading annotations

### ISSUE THREAD

**Issue by Reasat** [CancerDataScience/CrowdsourcingDataset-Amgadetal2019#2]
I am facing an error while downloading the annotations using download_crowdsource_dataset.py. After the 48'th annotation, I receive

Downloading annotations (base mag): Slide 48 of 151 (TCGA-S3-AA15)
Traceback (most recent call last):
  File "download_crowdsource_dataset.py", line 218, in <module>
    main()
  File "download_crowdsource_dataset.py", line 197, in main
    download_jsons()
  File "download_crowdsource_dataset.py", line 152, in download_jsons
    "/annotation/item/" + cf.slides[slide_name]['_id'])
  File "/home/reasatt/miniconda3/lib/python3.7/site-packages/girder_client/__init__.py", line 471, in get
    return self.sendRestRequest('GET', path, parameters, jsonResp=jsonResp)
  File "/home/reasatt/miniconda3/lib/python3.7/site-packages/girder_client/__init__.py", line 459, in sendRestRequest
    return result.json()
  File "/home/reasatt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/home/reasatt/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/reasatt/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/reasatt/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 130 (char 505823)

**Comment by kheffah** [comment]
@Reasat Thank you so much for pointing this out. This was a server timeout on our end. With Kitware's help, we've now fixed this issue.
